//export const API_URL = 'http://localhost:3001'
export const API_URL = 'http://34.41.177.151'
export const USER_ROLE = 1_000_001
export const ADMIN_ROLE = 1_000_000
export const VIEWER_ROLE = 1_000_002

export const serverEvents = {
  NEW_ALERT: 'NEW_ALERT',
  ACCESS_POINT: 'ACCESS_POINT',
  QUEUE_UPDATE: 'QUEUE_UPDATE',
  NEW_MEASUREMENT: 'NEW_MEASUREMENT',
  GENERATE_COMPLETE: 'GENERATE_COMPLETE',
  ACCESS_POINT_FULL: 'ACCESS_POINT_FULL'
}
